### PR TITLE
added php 8.1 to ci

### PR DESCRIPTION
**Pull request by AlessandroMinoccheri**

### CODE REVIEW

**Comment by JellyBellyDev** [comment]
Can you solve conflicts?

**Comment by AlessandroMinoccheri** [comment]
I have solved conflicts @JellyBellyDev but we still have some problems in some steps.

**Comment by JellyBellyDev** [comment]
@AlessandroMinoccheri I think that we resolve this when we bump ours dependencies to use `psr/cache` v2|v3.  
I have the same problem with the bump to sf6!

**Comment by AlessandroMinoccheri** [comment]
Yes, I have the same thought, as soon as possible I try to update dependencies!

**Comment by JellyBellyDev** [comment]
I'm waiting for https://github.com/BitbucketPHP/Client/issues/76 to complete https://github.com/PUGX/badge-poser/pull/691

**Comment by AlessandroMinoccheri** [comment]
@JellyBellyDev I think that I have to wait until we bump to Symfony6

**Pull request closed without merging**
