### PR TITLE
Adds a .gitattributes badge

### PR DESCRIPTION
**Pull request by raphaelstolt**
Adds a `.gitattributes` badge to indicate the quality of release/dist archives (i.e. if they contain irrelevant artifacts like `*.md` files or the `test*/` directory).

### CODE REVIEW

**Comment by liuggio** [comment]
hi @raphaelstolt this is a great idea!
please can you fix the test?

**Comment by raphaelstolt** [comment]
Will do.

**Comment by raphaelstolt** [comment]
@liuggio Fixed the tests and did a forced push.

**Comment by raphaelstolt** [comment]
What's the 411 on this one?

**Comment by liuggio** [comment]
Great thanks a lot sorry for the delay

**Comment by raphaelstolt** [comment]
When will this one be live/available at https://poser.pugx.org?

**Pull request merged**
