### PR TITLE
🔧 fix phpstan config

### PR DESCRIPTION
**Pull request by garak**

### CODE REVIEW

**Comment by garak** [comment]
I'm a bit confused... [this workflow](https://app.circleci.com/pipelines/github/PUGX/badge-poser/219/workflows/60913af2-97fa-40c2-abc4-1c4379302a09/jobs/803) says that we should remove error, while [this other workflow](https://app.circleci.com/pipelines/github/PUGX/badge-poser/221/workflows/d7523320-540e-4bbf-a7b6-6e9eb1916d1a/jobs/815) says that the same error is still present
😕

**Comment by AlessandroMinoccheri** [comment]
It's a strange problem, we can try to remove null from return type? I would suggest following phpstan errors to pass these tests. Is it possible?

**Comment by garak** [comment]
> It's a strange problem, we can try to remove null from return type? I would suggest following phpstan errors to pass these tests. Is it possible?

We can't remove null from the return type, since Redis can actually return a null value.

**Comment by AlessandroMinoccheri** [comment]
Yes, we can't remove null, we should ignore the error but we get another error that is not correct for me. What do you think @JellyBellyDev ?

**Comment by JellyBellyDev** [comment]
This situation is very strange... if we restore the ignore inside `phpstan-baseline.neon` what is the error?

**Comment by garak** [comment]
> This situation is very strange... if we restore the ignore inside `phpstan-baseline.neon` what is the error?

Situation with baseline is the first I linked above. By the way, my local environment confirms that error (but it's green in the second situation, the one I'm proposing in this PR)

**Comment by JellyBellyDev** [comment]
Close PR, because [this](https://github.com/PUGX/badge-poser/pull/385) fix che issue!

**Pull request closed without merging**
