### PR TITLE
Customize error pages

### LINKED ISSUE #281: Customize error pages
Our current error pages are the default one (see for example attached image with 500 error).
It would be nice to customize such pages
Schermata da 2020-03-25 14-52-44

### PR DESCRIPTION
**Pull request by JellyBellyDev**
[feat/customize-error-pages 0ca1abf] Customize error pages

close #281 

preview: 

Schermata 2020-05-18 alle 16 25 12

### CODE REVIEW

**Comment by JellyBellyDev** [comment]
> We should provide an error500 page that does not rely on twig (e.g. in pure and complete HTML).
> This is needed because we can't know in advance if a 500 error is due to twig

tips?

**Comment by garak** [comment]
> tips?

Just add a file named `error500.html.twig` (twig extension is irrelevant, but needed).
Put inside such file a full-HTML page. Also images need to be self-contained (e.g. provided via base64-encoded string) since we can't know in advance if normal images will be available at error time. I usually allow for extra-files only when provided via cdn, since we can safely suppose that the rest of Internet i still working 😉

**Comment by JellyBellyDev** [comment]
> Just add a file named `error500.html.twig` (twig extension is irrelevant, but needed).
> Put inside such file a full-HTML page. Also images need to be self-contained (e.g. provided via base64-encoded string) since we can't know in advance if normal images will be available at error time. I usually allow for extra-files only when provided via cdn, since we can safely suppose that the rest of Internet is still working 😉

Sorry but `templates/bundles/TwigBundle/Exception/error.html.twig` works for all errors: https://symfony.com/doc/current/controller/error_pages.html#overriding-the-default-error-templates
Why create a special file for manage only error page 500?

**Comment by garak** [comment]
I know, it's an edge case, but error 500 can happen for unpredictable reasons.
For example: suppose that `base.html.twig` file is somehow deleted from server, we need to be able to deliver a 500 error page that don't rely on such file.

**Comment by JellyBellyDev** [comment]
> I know, it's an edge case, but error 500 can happen for unpredictable reasons.
> For example: suppose that `base.html.twig` file is somehow deleted from server, we need to be able to deliver a 500 error page that don't rely on such file.

done! 🚀

**Pull request merged**
