### PR TITLE
fixup(method): Close #330

### LINKED ISSUE #330: Symfony\Component\HttpKernel\Exception\MethodNotAllowedHttpException: No route found for "OPTIONS /laravel/framework/license.svg": Method Not Allowed (Allow: GET)
Sentry Issue: [BADGE-POSER-X](https://sentry.io/organizations/pugx/issues/1675764711/?referrer=github_integration)

```
Symfony\Component\Routing\Exception\MethodNotAllowedException: 
  File "/public/index.php", line 25
    $response = $kernel->handle($request);
...
(7 additional frame(s) were not displayed)

Symfony\Component\HttpKernel\Exception\MethodNotAllowedHttpException: No route found for "OPTIONS /laravel/framework/license.svg": Method Not Allowed (Allow: GET)
  File "/public/index.php", line 25
    $response = $kernel->handle($request);
...
(4 additional frame(s) were not displayed)
```

### PR DESCRIPTION
**Pull request by JellyBellyDev**
[fixup/issues-330 ff00789] fixup(method): Close #330

### CODE REVIEW

**Comment by garak** [comment]
So, are we removing the limitation of methods just for the sake of avoiding errors?

**Comment by JellyBellyDev** [comment]
> So, are we removing the limitation of methods just for the sake of avoiding errors?

No, we are allowing any users to request a badge also using all possible verbs. Do not you agree?

**Comment by garak** [comment]
I think that the only verb that makes sense for our routes is "GET".
Allowing for other verbs is just like allowing for wrong URLs just because someone is trying to call them

**Comment by JellyBellyDev** [comment]
> I think that the only verb that makes sense for our routes is "GET".
> Allowing for other verbs is just like allowing for wrong URLs just because someone is trying to call them

ok! You've convinced me!

**Pull request closed without merging**
