### PR TITLE
add php-cs-fixer

### PR DESCRIPTION
**Pull request by garak**
I didn't include fixes.
Here is a preview, let me know:
```
 1) src/EventListener/BadgeSubscriber.php (phpdoc_no_package, phpdoc_summary, yoda_style, binary_operator_spaces, phpdoc_separation, ordered_imports)
   2) src/EventListener/StatsSubscriber.php (no_unneeded_control_parentheses, phpdoc_no_package, yoda_style, binary_operator_spaces)
   3) src/Kernel.php (void_return)
   4) src/Service/SnippetGeneratorInterface.php (phpdoc_no_package, phpdoc_summary)
   5) src/Service/SnippetGenerator.php (phpdoc_no_package, phpdoc_summary, phpdoc_var_without_name, trailing_comma_in_multiline_array, binary_operator_spaces, phpdoc_separation, phpdoc_align)
   6) src/Service/CachedClient.php (phpdoc_no_package, phpdoc_summary, single_quote, binary_operator_spaces)
   7) src/Stats/Reader/ReaderInterface.php (phpdoc_no_package, phpdoc_summary)
   8) src/Stats/Reader/RedisReader.php (phpdoc_no_package, phpdoc_summary, phpdoc_separation)
   9) src/Stats/Reader/NullReader.php (phpdoc_no_package, phpdoc_summary)
  10) src/Stats/Persister/PersisterInterface.php (phpdoc_no_package, phpdoc_summary)
  11) src/Stats/Persister/RedisPersister.php (phpdoc_no_package, method_argument_space, phpdoc_summary, phpdoc_separation, phpdoc_align)
  12) src/Stats/Persister/NullPersister.php (class_attributes_separation, phpdoc_no_package, phpdoc_summary, phpdoc_separation)
  13) src/Contributors/Service/Repository.php (phpdoc_no_package, phpdoc_summary, phpdoc_separation, no_extra_blank_lines)
  14) src/Contributors/Service/RepositoryInterface.php (phpdoc_no_package, phpdoc_summary, single_blank_line_before_namespace, single_blank_line_at_eof)
  15) src/Contributors/Command/UpdateCommand.php (void_return, phpdoc_no_package, phpdoc_summary, single_blank_line_before_namespace, single_blank_line_at_eof)
  16) src/Contributors/Model/Contributor.php (class_attributes_separation, phpdoc_no_package, phpdoc_summary, self_accessor)
  17) src/Badge/Service/TextNormalizer.php (phpdoc_no_package, pow_to_exponentiation, concat_space, modernize_types_casting, binary_operator_spaces, phpdoc_separation, braces)
  18) src/Badge/Service/ImageFactory.php (phpdoc_no_package, phpdoc_summary, phpdoc_var_without_name, phpdoc_separation, ordered_imports)
  19) src/Badge/Service/NormalizerInterface.php (phpdoc_no_package)
  20) src/Badge/Infrastructure/Package/PackageRepository.php (phpdoc_no_package, phpdoc_summary, no_leading_import_slash, ordered_imports)
  21) src/Badge/Infrastructure/ResponseFactory.php (phpdoc_no_package, phpdoc_summary, phpdoc_separation, phpdoc_align, single_blank_line_before_namespace, ordered_imports)
  22) src/Badge/Model/Image.php (phpdoc_no_package, phpdoc_summary, single_quote, self_accessor, phpdoc_separation)
  23) src/Badge/Model/UseCase/CreateLicenseBadge.php (phpdoc_no_package, phpdoc_summary, lowercase_keywords, phpdoc_separation, phpdoc_align)
  24) src/Badge/Model/UseCase/CreateComposerLockBadge.php (phpdoc_no_package, concat_space, phpdoc_summary, binary_operator_spaces, phpdoc_separation, phpdoc_align, single_blank_line_before_namespace)
  25) src/Badge/Model/UseCase/CreateDownloadsBadge.php (phpdoc_no_package, single_quote, lowercase_keywords, phpdoc_separation, no_extra_blank_lines, phpdoc_align, ordered_imports)
  26) src/Badge/Model/UseCase/CreateVersionBadge.php (phpdoc_no_package, phpdoc_summary, lowercase_keywords, phpdoc_separation, phpdoc_align, single_blank_line_before_namespace)
  27) src/Badge/Model/UseCase/CreateGitAttributesBadge.php (phpdoc_no_package, concat_space, phpdoc_summary, binary_operator_spaces, phpdoc_separation, phpdoc_align, single_blank_line_before_namespace)
  28) src/Badge/Model/UseCase/CreateErrorBadge.php (phpdoc_no_package, lowercase_keywords, binary_operator_spaces, phpdoc_separation, phpdoc_align, ordered_imports)
  29) src/Badge/Model/UseCase/BaseCreatePackagistImage.php (phpdoc_no_package, phpdoc_summary, phpdoc_separation, no_extra_blank_lines, phpdoc_align, braces)
  30) src/Badge/Model/Package.php (void_return, phpdoc_no_package, concat_space, self_accessor, no_extra_blank_lines, braces)
  31) src/Badge/Model/Badge.php (class_attributes_separation, phpdoc_no_package, array_syntax, concat_space, phpdoc_annotation_without_dot, phpdoc_summary, single_quote, lowercase_keywords, phpdoc_separation)
  32) src/Badge/Model/PackageRepositoryInterface.php (phpdoc_no_package, phpdoc_summary, no_extra_blank_lines)
  33) src/Controller/SnippetController.php (no_unneeded_control_parentheses, phpdoc_no_package, phpdoc_summary, yoda_style, phpdoc_separation, phpdoc_align)
  34) src/Controller/PackagistController.php (phpdoc_no_package, array_syntax, phpdoc_summary, phpdoc_separation, phpdoc_align)
  35) src/Controller/Badge/VersionController.php (phpdoc_no_package, concat_space, phpdoc_separation, no_extra_blank_lines, phpdoc_align, ordered_imports)
  36) src/Controller/Badge/LicenseController.php (phpdoc_no_package, phpdoc_separation, phpdoc_align, ordered_imports)
  37) src/Controller/Badge/ComposerLockController.php (phpdoc_no_package, yoda_style, phpdoc_separation, phpdoc_align, ordered_imports)
  38) src/Controller/Badge/DownloadsController.php (phpdoc_no_package, phpdoc_separation, phpdoc_align, ordered_imports)
  39) src/Controller/Badge/GitAttributesController.php (phpdoc_no_package, phpdoc_summary, yoda_style, phpdoc_separation, phpdoc_align, ordered_imports)
  40) src/Controller/HomeController.php (phpdoc_no_package, phpdoc_summary, trailing_comma_in_multiline_array, phpdoc_separation, ordered_imports)
  41) tests/EventListener/StatsSubscriberTest.php (phpdoc_no_package, array_syntax, phpdoc_summary)
  42) tests/Service/SnippetGeneratorStub.php (phpdoc_no_package, phpdoc_summary)
  43) tests/Service/SnippetGeneratorTest.php (void_return, phpdoc_no_package, phpdoc_summary, trailing_comma_in_multiline_array, binary_operator_spaces, no_whitespace_in_blank_line)
  44) tests/Contributors/Service/RepositoryTest.php (void_return, phpdoc_no_package, concat_space, phpdoc_summary, single_quote, trailing_comma_in_multiline_array, yoda_style, php_unit_construct, no_extra_blank_lines, single_blank_line_before_namespace, single_blank_line_at_eof)
  45) tests/Contributors/Command/UpdateCommandTest.php (void_return, phpdoc_no_package, phpdoc_summary, blank_line_before_statement, single_blank_line_before_namespace, single_blank_line_at_eof)
  46) tests/Contributors/Model/ContributorTest.php (void_return, phpdoc_no_package, phpdoc_summary, no_extra_blank_lines, single_blank_line_before_namespace, single_blank_line_at_eof)
  47) tests/Badge/Service/TextNormalizerTest.php (void_return, phpdoc_no_package, php_unit_no_expectation_annotation, array_syntax, phpdoc_summary, php_unit_expectation, no_unused_imports)
  48) tests/Badge/Model/ParseStabilityTest.php (phpdoc_no_package, array_syntax, phpdoc_summary, phpdoc_separation, ordered_imports)
  49) tests/Badge/Model/BadgeTest.php (void_return, phpdoc_no_package, method_argument_space, phpdoc_summary, ordered_imports)
  50) tests/Badge/Model/UseCase/CreateDownloadsBadgeTest.php (void_return, phpdoc_no_package, phpdoc_summary)
  51) tests/Badge/Model/UseCase/CreateLicenseBadgeTest.php (void_return, phpdoc_no_package, phpdoc_summary)
  52) tests/Badge/Model/UseCase/CreateComposerLockBadgeTest.php (void_return, phpdoc_no_package, array_syntax, method_argument_space, phpdoc_summary, ordered_imports)
  53) tests/Badge/Model/UseCase/CreateVersionBadgeTest.php (void_return, phpdoc_no_package, phpdoc_summary)
  54) tests/Controller/SnippetControllerTest.php (void_return, phpdoc_no_package, method_argument_space, phpdoc_summary)
  55) tests/Controller/Badge/VersionControllerTest.php (void_return, phpdoc_no_package, phpdoc_summary)
  56) tests/Controller/Badge/GitAttributesBadgeControllerTest.php (void_return, phpdoc_no_package, phpdoc_summary)
  57) tests/Controller/Badge/LicenseControllerTest.php (void_return, phpdoc_no_package, phpdoc_summary)
  58) tests/Controller/Badge/DownloadsControllerTest.php (void_return, phpdoc_no_package, phpdoc_summary)
  59) tests/Controller/Badge/ComposerLockControllerTest.php (class_attributes_separation, void_return, phpdoc_no_package, phpdoc_summary)
  60) tests/Controller/PackagistControllerTest.php (void_return, phpdoc_no_package, phpdoc_summary)

```

### CODE REVIEW

**Comment by garak** [comment]
@JellyBellyDev I'm not a big fan of composer commands

**Comment by JellyBellyDev** [comment]
how would you like to have the fix run automatically?

**Comment by garak** [comment]
We don't. Just use automated hooks, like for testing.
Of course, we can promote using php-cs-fixer in docs

**Comment by JellyBellyDev** [comment]
👍🏻

**Pull request merged**
