### PR TITLE
update php-cs-fixer

### PR DESCRIPTION
**Pull request by garak**

### CODE REVIEW

**Comment by JellyBellyDev** [comment]
why did the CI break?

**Comment by garak** [comment]
> why did the CI break?

Because php-cs-fixer changed occurrences of `\Exception` to `Exception` :-(

**Comment by JellyBellyDev** [comment]
> > why did the CI break?
> 
> Because php-cs-fixer changed occurrences of `\Exception` to `Exception` :-(

without add the use on top? ;(

**Comment by garak** [comment]
Found related issue: https://github.com/FriendsOfPHP/PHP-CS-Fixer/issues/5684

**Review by JellyBellyDev — APPROVED** [review]
LGTM 👍

**Pull request merged**
