### PR TITLE
[WIP] Add dependents and suggestors badges

### PR DESCRIPTION
**Pull request by chadicus**

### CODE REVIEW

**Comment by JellyBellyDev** [comment]
@liuggio and @garak what do you think about of adding this feature in v3? Could it make sense?

**Comment by JellyBellyDev** [comment]
@chadicus would you like to add this feature in [v3](https://github.com/PUGX/badge-poser/tree/release/v3.0.0)? Otherwise I'll take care of it!
Thank you

**Comment by chadicus** [comment]
@JellyBellyDev I'm good with either. Honestly I had forgotten i had started this PR. I had plans to add a suggeters badge as well. it took a very long time to get both the [suggesters](https://github.com/KnpLabs/packagist-api/pull/40) and [dependents](https://github.com/KnpLabs/packagist-api/pull/39) properties added to the packagist api.

**Comment by JellyBellyDev** [comment]
Great, we are waiting for your PR on v3! ;)

**Comment by chadicus** [comment]
@JellyBellyDev  should I close this and reopen against the `release/v3.0.0` branch?

**Comment by JellyBellyDev** [comment]
@chadicus Yes thanks!

**Pull request closed without merging**
