### PR TITLE
feat: bump to sf7 and php83

### PR DESCRIPTION
**Pull request by JellyBellyDev**
- [x] bump symfony 7
- [x] bump php 8.3

### CODE REVIEW

**Review by garak — CHANGES_REQUESTED** [review]
but why not PHP 8.3?

**Comment by JellyBellyDev** [comment]
> but why not PHP 8.3?

it is not too early? :)

**Comment by garak** [comment]
> > but why not PHP 8.3?
> 
> it is not too early? :)

Is it? I already migrated all of my projects, it's been six weeks since it's out!

**Comment by JellyBellyDev** [comment]
@garak could you help me fix the tests as I don't have much experience with phpunit 10?

**Comment by garak** [comment]
My advice is to stay on PHPUnit 9 for now.
Unfortunately, the Symfony PHPUnit bridge doesn't support version 10 yet

**Review by garak — APPROVED** [review]

**Pull request merged**
