### PR TITLE
pinning versions

### PR DESCRIPTION
**Pull request by fabiocicerchia**

### CODE REVIEW

**Comment by garak** [comment]
It seems to me that we're passing from one side to the opposite one: from no pinning at all to pinning to the patch version.
Can we stay in a reasonable middle ground? The minor version seems the optimal compromise.

**Comment by fabiocicerchia** [comment]
@garak no problems, it was easier to get the whole version, I'll iterate again to figure out which minor is available a tag, might be that not everywhere is possible to pin to minor though.

**Review by JellyBellyDev — APPROVED** [review]
LGTM 👍

**Review by garak — APPROVED** [review]
It's ok for me. But I don't get why some actions check are still in the queue, even after several hours...

**Comment by JellyBellyDev** [comment]
> It's ok for me. But I don't get why some actions check are still in the queue, even after several hours...

Also on master 😓

**Pull request merged**
